when:
  - author:
      teamIs:
        - rubik
      ignore:
        nameIs:
    assign:
      teams:
        - rubik
  - author:
      teamIs:
        - woo-fse
      ignore:
        nameIs:
    assign:
      teams:
        - woo-fse
  - author:
      teamIs:
        - flux
      ignore:
        nameIs:
    assign:
      teams:
        - flux
  - author:
      teamIs:
        - proton
      ignore:
        nameIs:
    assign:
      teams:
        - proton
  - author:
      teamIs:
        - mailpoet
      ignore:
        nameIs:
    assign:
      teams:
        - mailpoet
