# See https://github.com/shufo/auto-assign-reviewer-by-files/blob/main/README.md for configuration format

"*":
  - team: flux

".github/**/*":
  - team: flux

"bin/*":
  - team: flux

"docs/**/*":
  - team: developer-advocacy

"packages/js/api/**/*":
  - team: solaris

"packages/js/e2e-utils/**/*":
  - team: solaris

"packages/js/e2e-environment/**/*":
  - team: solaris

"packages/js/api-core-tests/**/*":
  - team: solaris

"packages/js/e2e-core-tests/**/*":
  - team: solaris

"packages/js/admin-e2e-tests/**/*":
  - team: solaris

"packages/js/components/**/*":
  - team: woo-fse
  - team: ghidorah

"packages/js/csv-export/**/*":
  - team: woo-fse

"packages/js/currency/**/*":
  - team: fractal

"packages/js/customer-effort-score/**/*":
  - team: woo-fse
  - team: ghidorah

"packages/js/data/**/*":
  - team: woo-fse
  - team: ghidorah

"packages/js/date/**/*":
  - team: woo-fse

"packages/js/dependency-extraction-webpack-plugin/**/*":
  - team: flux

"packages/js/eslint-plugin/**/*":
  - team: flux

"packages/js/experimental/**/*":
  - team: woo-fse

"packages/js/explat/**/*":
  - team: woo-fse
  - team: ghidorah

"packages/js/navigation/**/*":
  - team: woo-fse

"packages/js/number/**/*":
  - team: woo-fse

"packages/js/onboarding/**/*":
  - team: ghidorah

"packages/js/product-editor/**/*":
  - team: woo-fse

"packages/js/tracks/**/*":
  - team: woo-fse
  - team: ghidorah

"plugins/woocommerce/**/*":
  - team: proton

"plugins/woocommerce/templates/**/*":
  - team: rubik
  - team: woo-fse

"plugins/woocommerce/templates/emails/**/*":
  - team: proton

"plugins/woocommerce/src/Blocks/**/*":
  - team: rubik
  - team: woo-fse

"plugins/woocommerce/src/StoreApi/**/*":
  - team: rubik
  - team: woo-fse

"plugins/woocommerce/client/admin/**/*":
  - team: woo-fse
  - team: ghidorah

"plugins/woocommerce/client/blocks/**/*":
  - team: rubik
  - team: woo-fse

"plugins/woocommerce-beta-tester/**/*":
  - team: ghidorah

"tools/**/*":
  - team: flux

'**/composer.json':
  - team: flux

'**/package.json':
  - team: flux

"php/blueprint":
  - team: ghidorah

"php/remote-specs-validation":
  - team: ghidorah

"plugins/woocommerce-beta-tester":
  - team: ghidorah

"plugins/Woocommerce":
  - team: ghidorah

"plugins/Woocommerce/includes/admin/class-wc-admin-setup-wizard":
  - team: ghidorah

"plugins/Woocommerce/includes/admin/notes/*":
  - team: ghidorah

"plugins/Woocommerce/includes/react-admin/*":
  - team: ghidorah

"plugins/Woocommerce/patterns/coming-soon-*.php":
  - team: ghidorah

"plugins/Woocommerce/patterns/page-coming-soon-*.php":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/Notes/*":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/DataSourcePoller.php":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/DeprecatedClassFacade.php":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/FeaturePlugin.php":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/Loader.php":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/PageController.php":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/PluginsHelper.php":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/PluginsInstaller.php":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/WCAdminHelper.php":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/Features/OnboardingTasks/*":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/Features/PaymentGatewaySuggestions/*":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/Features/ShippingPartnerSuggestions/*":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/Features/LaunchYourStore/*":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/Features/Settings/*":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/Features/Blueprint/*":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/RemoteInboxNotifications/*":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/RemoteSpecs/*":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/API/Notes.php":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/API/Onboarding*.php":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/API/ShippingPartnerSuggestions.php":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/API/Experiments.php":
  - team: ghidorah

"plugins/Woocommerce/src/Admin/API/LaunchYourStore.php":
  - team: ghidorah

"plugins/Woocommerce/src/Internal/Admin/Onboarding/*":
  - team: ghidorah

"plugins/Woocommerce/src/Internal/Admin/RemoteFreeExtensions/*":
  - team: ghidorah

"plugins/Woocommerce/src/Internal/Admin/MobileAppBanner.php":
  - team: ghidorah

"plugins/Woocommerce/src/Internal/Admin/RemoteInboxNotifications.php":
  - team: ghidorah

"plugins/Woocommerce/src/Internal/Admin/Homescreen.php":
  - team: ghidorah

"plugins/Woocommerce/src/Internal/Admin/Settings/*":
  - team: ghidorah

"plugins/Woocommerce/src/Internal/Admin/Notes/*":
  - team: ghidorah

"plugins/Woocommerce/src/Internal/Admin/Loader.php":
  - team: ghidorah

"plugins/Woocommerce/src/Internal/Admin/WCAdminAssets.php":
  - team: ghidorah

"plugins/Woocommerce/src/Internal/Logging/RemoteLogger.php":
  - team: ghidorah

"plugins/Woocommerce/src/Internal/ComingSoon/*":
  - team: ghidorah

"plugins/Woocommerce/src/Internal/McStats.php":
  - team: ghidorah

"plugins/Woocommerce/src/Internal/RemoteLogger.php":
  - team: ghidorah