name: Install and Build (Composite)
description: Installs and builds WooCommerce.
inputs:
  working_directory:
    required: false
    description: The directory to target.
    default: ./
  workflow_cache:
    required: true
    description: The workflow cache key.

runs:
  using: "composite"
  steps:
    - name: Install PNPM
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: npm install -g pnpm@^6.24.2

    - name: Turborepo Build caching
      uses: actions/cache@v3
      with:
        path: |
          **/.cache/turbo
        key: ${{ runner.os }}-${{ inputs.workflow_cache }}-${{ hashFiles('**/turbo-build.log') }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: COMPOSER_NO_DEV=1 pnpm install

    - name: Run build
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: pnpm -- turbo run build --filter=woocommerce
