name: Add Community Label, Assign Reviewers

on:
    pull_request_target:
        types: [opened, ready_for_review]
    issues:
        types: [opened]

concurrency:
    # For pull_request_target, cancel concurrent jobs with the same type and branch.
    # Don't cancel for other events, by grouping on the unique run_id.
    group: community-label-${{ github.event_name }}-${{ github.event.action }}-${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.ref || github.run_id }}
    cancel-in-progress: true

permissions:
    contents: read
    pull-requests: write
    issues: write

jobs:
    add-community-label:
        name: Add Community Label
        if: ${{ github.event.action == 'opened' }}
        runs-on: ubuntu-latest
        permissions:
        steps:
            # github.event.issue.author_association, github.event.pull_request.author_association: COLLABORATOR, MEMBER
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4

            - name: Check if user is a community contributor
              id: check
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  npm --prefix .github/workflows/scripts install @octokit/action@~6.1.0 @actions/core@~1.10.1
                  node .github/workflows/scripts/is-community-contributor.js

            # TODO: relocate under 'add-reviews'
            - name: 'Assign reviewers'
              if: github.event.pull_request && steps.check.outputs.is-community == 'yes'
              uses: shufo/auto-assign-reviewer-by-files@f5f3db9ef06bd72ab6978996988c6462cbdaabf6
              with:
                  config: '.github/project-community-pr-assigner.yml'
                  token: ${{ secrets.PR_ASSIGN_TOKEN }}

    add-reviews:
      name: Automate assigning team for review
      if: ${{ github.event.pull_request && github.event.pull_request.draft == false && github.actor != 'dependabot[bot]' }}
      runs-on: ubuntu-latest
      steps:
        - name: Check config and assign reviews
          continue-on-error: ${{ ( github.event.pull_request.head.repo.fork && 'true' ) || 'false' }}
          uses: acq688/Request-Reviewer-For-Team-Action@v1.1
          with:
            config: '.github/automate-team-review-assignment-config.yml'
            GITHUB_TOKEN: ${{ secrets.PR_ASSIGN_TOKEN }}
