name: Add community label, Assign reviewers

on:
    pull_request_target:
        types: [opened, ready_for_review]
    issues:
        types: [opened]

concurrency:
    group: automate-team-review-assignment-${{ github.event_name }}-${{ github.event.pull_request.number || github.event.issue.number }}
    cancel-in-progress: true

permissions:
    contents: read
    pull-requests: write
    issues: write

jobs:
    add-community-label:
        name: Add community label
        if: ${{ github.event.action == 'opened' }}
        runs-on: ubuntu-latest
        steps:
            - name: Check if community contribution
              id: check
              run: |
                  association='${{ github.event.pull_request.author_association || github.event.issue.author_association }}'
                  if [[ $association == 'COLLABORATOR' || $association == 'MEMBER' ]]; then
                      contributor='no'
                  else
                      contributor='yes'
                      if [[ '${{ github.event.pull_request.user.login || github.event.issue.user.login }}' == 'gglobalstep' ]]; then
                          contributor='no'
                      fi
                  fi
                  echo "contributor=$contributor" >> $GITHUB_OUTPUT

            - name: Add community label
              if: ${{ steps.check.outputs.contributor == 'yes' }}
              uses: actions/github-script@v7
              with:
                  script: |
                      octokit.rest.issues.addLabels({
                          issue_number: ${{ github.event.pull_request.number || github.event.issue.number }},
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          labels: [ 'type: community contribution' ]
                      })

    assign-reviewers:
      name: Assign reviewers
      if: ${{ github.event.pull_request }}
      runs-on: ubuntu-latest
      steps:
        - name: Check if community contribution
          id: check
          run: |
            association='${{ github.event.pull_request.author_association }}'
            if [[ $association == 'COLLABORATOR' || $association == 'MEMBER' ]]; then
                contributor='no'
            else
                contributor='yes'
            fi
            echo "contributor=$contributor" >> $GITHUB_OUTPUT

        - name: Assign reviewers for a community PR
          if: ${{ steps.check.outputs.contributor == 'yes' }}
          uses: shufo/auto-assign-reviewer-by-files@f5f3db9ef06bd72ab6978996988c6462cbdaabf6
          with:
              config: '.github/project-community-pr-assigner.yml'
              token: ${{ secrets.PR_ASSIGN_TOKEN }}

        - name: Assign reviewers for a teams PR
          if: ${{ steps.check.outputs.contributor == 'no' && github.event.pull_request.draft == false }}
          continue-on-error: ${{ ( github.event.pull_request.head.repo.fork && 'true' ) || 'false' }}
          uses: acq688/Request-Reviewer-For-Team-Action@v1.1
          with:
              config: '.github/automate-team-review-assignment-config.yml'
              GITHUB_TOKEN: ${{ secrets.PR_ASSIGN_TOKEN }}
