name: Blocks Playwright Tests Template

on:
    workflow_call:
        inputs:
            name:
                required: true
                type: string
            config:
                required: true
                type: string
            results-folder:
                required: true
                type: string
            shard-index:
                required: true
                type: number
            shard-total:
                required: true
                type: number

jobs:
    e2e:
        name: ${{ inputs.name }} [${{ inputs.shard-index }}/${{ inputs.shard-total }}]
        timeout-minutes: 60
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: plugins/woocommerce-blocks
        steps:
            - uses: actions/checkout@v3

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                  install: '@woocommerce/plugin-woocommerce...'
                  build: '@woocommerce/plugin-woocommerce'

            - name: Install Playwright
              run: pnpm --filter='@woocommerce/block-library' exec playwright install --with-deps

            - name: Start wp-env
              run: pnpm --filter='@woocommerce/block-library' env:start

            - name: Run Playwright tests
              working-directory: plugins/woocommerce-blocks
              run: pnpm playwright test --config=tests/e2e/${{ inputs.config }} --shard ${{ inputs.shard-index }}/${{ inputs.shard-total }}

            - uses: actions/upload-artifact@v3
              if: ${{ failure() }}
              with:
                  name: playwright-report-${{ inputs.results-folder }}
                  path: plugins/woocommerce-blocks/tests/e2e/artifacts/${{ inputs.results-folder }}
                  if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
