name: Run Blocks Playwright Tests
on:
    pull_request:
        paths:
            - 'plugins/woocommerce-blocks/**'
            - 'plugins/woocommerce/src/Blocks/**'
            - 'plugins/woocommerce/templates/**'
            - 'plugins/woocommerce/patterns/**'
    # Allow manually triggering the workflow.
    workflow_dispatch:


env:
    FORCE_COLOR: 1

jobs:
    e2e:
        name: ${{ matrix.name }} [${{ matrix.shardIndex }}/${{ matrix.shardTotal }}]
        timeout-minutes: 60
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: plugins/woocommerce-blocks
        strategy:
            fail-fast: false
            matrix:
                config: [
                    playwright.config.ts,
                    playwright.classic-theme.config.ts,
                    playwright.side-effects.config.ts,
                    playwright.block-theme-with-templates.config.ts
                ]
                include:
                    - config: playwright.config.ts
                      name: Default (Block) Theme
                      shardIndex: [1, 2, 3, 4, 5]
                      shardTotal: 5
                    - config: playwright.classic-theme.config.ts
                      name: Classic Theme
                      shardIndex: [1, 2, 3, 4]
                      shardTotal: 4
                    - config: playwright.side-effects.config.ts
                      name: Side Effects
                      shardIndex: [1, 2, 3, 4, 5]
                      shardTotal: 5
                    - config: playwright.block-theme-with-templates.config.ts
                      name: Block Theme With Templates
                      shardIndex: [1]
                      shardTotal: 1

        steps:
            - uses: actions/checkout@v3

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                  install: '@woocommerce/plugin-woocommerce...'
                  build: '@woocommerce/plugin-woocommerce'

            - name: Install Playwright
              run: pnpm --filter='@woocommerce/block-library' exec playwright install --with-deps

            - name: Start wp-env
              run: pnpm --filter='@woocommerce/block-library' env:start

            - name: Run Playwright tests
              working-directory: plugins/woocommerce-blocks
              run: pnpm playwright test --config=tests/e2e/${{ matrix.config }} --shard ${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

            - uses: actions/upload-artifact@v3
              if: ${{ failure() }}
              with:
                  name: playwright-report-${{ matrix.config.name }}
                  path: plugins/woocommerce-blocks/tests/e2e/artifacts/${{ matrix.config.resultPath }}
                  if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
