name: Run Blocks Playwright Tests

on:
    pull_request:
        paths:
            - '.github/workflows/blocks-playwright.yml' # This file
            - 'plugins/woocommerce-blocks/**'
            - 'plugins/woocommerce/src/Blocks/**'
            - 'plugins/woocommerce/templates/**'
            - 'plugins/woocommerce/patterns/**'

    # Allow manually triggering the workflow.
    workflow_dispatch:

env:
    FORCE_COLOR: 1

jobs:
    default-theme:
        strategy:
            fail-fast: false
            matrix:
                shard-index: [1, 2, 3, 4, 5]
                shard-total: [5]
        uses: ./.github/workflows/blocks-playwright-template.yml
        with:
            name: Default (Block) Theme
            config: playwright.config.ts
            results-folder: test-results
            shard-index: ${{ matrix.shard-index }}
            shard-total: ${{ matrix.shard-total }}

    classic-theme:
        strategy:
            fail-fast: false
            matrix:
                shard-index: [1, 2, 3, 4]
                shard-total: [4]
        uses: ./.github/workflows/blocks-playwright-template.yml
        with:
            name: Classic Theme
            config: playwright.classic-theme.config.ts
            results-folder: test-results-classic-theme
            shard-index: ${{ matrix.shard-index }}
            shard-total: ${{ matrix.shard-total }}

    side-effects:
        strategy:
            fail-fast: false
            matrix:
                shard-index: [1, 2, 3, 4, 5]
                shard-total: [5]
        uses: ./.github/workflows/blocks-playwright-template.yml
        with:
            name: Side Effects
            config: playwright.side-effects.config.ts
            results-folder: test-results-side-effects
            shard-index: ${{ matrix.shard-index }}
            shard-total: ${{ matrix.shard-total }}

    block-theme-with-templates:
        strategy:
            fail-fast: false
            matrix:
                shard-index: [1]
                shard-total: [1]
        uses: ./.github/workflows/blocks-playwright-template.yml
        with:
            name: Block Theme With Templates
            config: playwright.block-theme-with-templates.config.ts
            results-folder: test-results-block-theme-with-templates
            shard-index: ${{ matrix.shard-index }}
            shard-total: ${{ matrix.shard-total }}
