name: Run Blocks Playwright Tests

on:
    pull_request:
        paths:
            - '.github/workflows/blocks-playwright.yml' # This file
            - 'plugins/woocommerce-blocks/**'
            - 'plugins/woocommerce/src/Blocks/**'
            - 'plugins/woocommerce/templates/**'
            - 'plugins/woocommerce/patterns/**'

    # Allow manually triggering the workflow.
    workflow_dispatch:

env:
    FORCE_COLOR: 1

jobs:
    default-theme:
        - uses: ./.github/actions/blocks-playwright-template
          with:
              name: Default (Block) Theme
              config: playwright.config.ts
              result-path: test-results
              shard-index: [1, 2, 3, 4, 5]
              shard-total: 5    
    classic-theme:
        - uses: ./.github/actions/blocks-playwright-template
          with:
              name: Classic Theme
              config: playwright.classic-theme.config.ts
              result-path: test-results-classic-theme
              shard-index: [1, 2, 3, 4]
              shard-total: 4
    side-effects:
        - uses: ./.github/actions/blocks-playwright-template
          with:
              name: Side Effects
              config: playwright.side-effects.config.ts
              result-path: test-results-side-effects
              shard-index: [1, 2, 3, 4, 5]
              shard-total: 5
    block-theme-with-templates:
        - uses: ./.github/actions/blocks-playwright-template
          with:
              name: Block Theme With Templates
              config: playwright.block-theme-with-templates.config.ts
              result-path: test-results-block-theme-with-templates
              shard-index: [1]
              shard-total: 1
