name: Blocks Playwright Tests

on:
    pull_request:
        paths:
            - '.github/workflows/blocks-playwright.yml' # This file
            - 'plugins/woocommerce-blocks/**'
            - 'plugins/woocommerce/src/Blocks/**'
            - 'plugins/woocommerce/templates/**'
            - 'plugins/woocommerce/patterns/**'
    # Allow manually triggering the workflow.
    workflow_dispatch:

env:
    FORCE_COLOR: 1

jobs:
    blocks-playwright-tests:
        name: Shard ${{ matrix.shardIndex }} of ${{ matrix.shardTotal }}
        timeout-minutes: 60
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: plugins/woocommerce-blocks
        strategy:
            fail-fast: false
            matrix:
                shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
                shardTotal: [10]

        steps:
            - uses: actions/checkout@v4

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                  install: '@woocommerce/plugin-woocommerce...'
                  build: '@woocommerce/plugin-woocommerce'

            - name: Install Playwright dependencies
              run: pnpm exec playwright install chromium --with-deps

            - name: Setup testing environment and start the server
              run: pnpm env:start

            - name: Run Playwright tests
              run: pnpm test:e2e --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

            - name: Upload blob report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: blob-report--${{ matrix.shardIndex }}
                  path: plugins/woocommerce-blocks/tests/e2e/artifacts/blob-report
                  retention-days: 1

    merge-reports:
        name: Merge Reports
        if: ${{ !cancelled() }}
        needs: [blocks-playwright-tests]

        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install Playwright
              run: npm install @playwright/test

            - name: Download blob reports
              uses: actions/download-artifact@v4
              with:
                  path: all-blob-reports
                  pattern: blob-report--*
                  merge-multiple: true

            - name: Merge into HTML Report
              run: npx playwright merge-reports --reporter html ./all-blob-reports

            - name: Upload HTML report
              uses: actions/upload-artifact@v4
              with:
                  name: html-report--attempt-${{ github.run_attempt }}
                  path: playwright-report
                  retention-days: 14
