name: 'CI'
on: 
  pull_request:
  push:
    branches:
      - 'trunk'
      - 'release/*'
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
jobs:
  project-jobs:
    # Since this is a monorepo, not every pull request or change is going to impact every project.
    # Instead of running CI tasks on all projects indiscriminately, we use a command to detect
    # which projects have changed and what kind of change occurred. This lets us build the
    # matrices that we can use to run CI tasks only on the projects that need them.
    name: 'Build Project Jobs'
    runs-on: 'ubuntu-20.04'
    outputs:
      lint: ${{ steps.project-jobs.outputs.lint }}
      test: ${{ steps.project-jobs.outputs.test }}
    steps:
      - uses: 'actions/checkout@v3'
        name: 'Checkout'
        with:
          fetch-depth: 0
      - uses: './.github/actions/setup-woocommerce-monorepo'
        name: 'Setup Monorepo'
        with:
          install: 'monorepo-utils...'
          build: 'monorepo-utils'
      - uses: actions/github-script@v6
        name: 'Build Matrix'
        id: 'project-jobs'
        with:
          script: |
            let baseRef = ${{ toJson( github.base_ref ) }};
            if ( baseRef ) {
              baseRef = 'origin/' + baseRef;
            }
            const child_process = require( 'child_process' );
            const jobs = JSON.parse(
              child_process.execSync( 'pnpm utils ci-jobs ' + baseRef, { encoding: 'utf8' } )
            );
            console.log( jobs );
            for ( const jobType in jobs ) {
              core.setOutput( jobType, JSON.stringify( jobs[ jobType ] ) );
            }
