name: Add New Issue/Pull Labels

on:
  pull_request_target:
    types: opened
  issues:
    types: opened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
permissions: {}

jobs:
  triage:
    name: Add awaiting triage
    if: github.event.issue
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v3
      # We want to delay the labeling of the issue so that the author has a change to add labels after issue creation.
      - name: 'Delay Labeling'
        run: sleep 3m
      # Make sure that the latest issue is pulled from the database rather than relying on the payload. This is
      # because the payload won't include any labels that were added after the issue was created.
      - uses: actions/github-script@v6
        id: latest-issue
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            core.setOutput('hasLabels', issue.data.labels.length > 0);
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.latest-issue.outputs.hasLabels == 'false'}}
        with:
          labels: 'status: awaiting triage'

  community:
    name: Add community contribution label
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6

      - name: Check if user is a community contributor
        id: check
        run: node .github/workflows/scripts/is-community-contributor.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'If community PR, assign a reviewer'
        if: github.event.pull_request && steps.check.outputs.is-community == 'yes'
        uses: shufo/auto-assign-reviewer-by-files@f5f3db9ef06bd72ab6978996988c6462cbdaabf6
        with:
          config: '.github/project-community-pr-assigner.yml'
          token: ${{ secrets.PR_ASSIGN_TOKEN }}
