name: Nightly builds
on:
  schedule:
    - cron: '0 0 * * *' # Run at 12 AM UTC.
  workflow_dispatch:

permissions: { }

jobs:
  build:
    if: github.repository_owner == 'woocommerce'
    name: Nightly builds
    strategy:
      fail-fast: false
      matrix:
        build: [ trunk ]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.build }}

      - name: Setup WooCommerce Monorepo
        uses: ./.github/actions/setup-woocommerce-monorepo

      - name: Build zip
        working-directory: plugins/woocommerce
        run: bash bin/build-zip.sh

      - name: Upload nightly build
        uses: WebFreak001/deploy-nightly@d147b5dbd2cb8245d2b5f83a41f5ebe9957575b4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/25945111/assets{?name,label}
          release_id: 25945111
          asset_path: plugins/woocommerce/woocommerce.zip
          asset_name: woocommerce-${{ matrix.build }}-nightly.zip
          asset_content_type: application/zip
          max_releases: 1
      
      # Update the release body so that the release edited trigger is fired. ci.yml will run tests on this event.
      - name: Update nightly release body
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const currentUTC = new Date().toUTCString();
            const releaseId = 25945111;
            const newBody = `Updated at ${currentUTC} UTC.`;
            await github.rest.releases.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
              body: newBody
            });

  update:
    name: Update nightly tag commit ref
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Update nightly tag
        uses: richardsimko/github-tag-action@e173a8ef8f54ab526a91dad6139a25efed62424c
        with:
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
