name: woocommerce/api JS Package Tests
description: Runs @woocommerce/api JS package tests when there are changes to the package.

on:
  pull_request:
    paths:
      - 'packages/js/api/**'
    paths-ignore:
      - '**.md'

jobs:
  package_js_api:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install PNPM and install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Run @woocommerce/api tests
        run: cd packages/js/api && npm test
