name: Compressed Size

on:
    pull_request:
        paths:
            - '**.jsx?'
            - '**.tsx?'
            - '**.css'
            - '**.scss'
            - '**package*.json'
            - '**.eslint*'
            - '**.prettier*'
            - '**.tsconfig*'
            - '**/webpack.config.js'
            - '.github/workflows/pr-assess-bundle-size.yml'

concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    build:
        name: Check Asset Sizes
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                  # Both install and build are handled by compressed-size-action.
                  install: false
                  build: false
            - uses: preactjs/compressed-size-action@f780fd104362cfce9e118f9198df2ee37d12946c
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  pattern: '{packages/js/**/build/**/*.js,packages/js/**/build/**/*.css,plugins/woocommerce/client/legacy/js/**/*.min.js,plugins/woocommerce/client/legacy/css/**/*.css,plugins/woocommerce-admin/build/**/*.min.js,plugins/woocommerce-admin/build/**/*.css,plugins/woocommerce-blocks/build/**/*.js}'
                  exclude: '{packages/js/dependency-extraction-webpack-plugin/,packages/js/*e2e*/,packages/js/*create*/,**/*.map,**/node_modules/**'
                  clean-script: 'distclean 2>/dev/null'
                  minimum-change-threshold: 100
