name: Run code coverage on PR
on:
  pull_request:
  workflow_dispatch:
defaults:
  run:
    shell: bash
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Code coverage (PHP 7.4, WP Latest)
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer
          extensions: mysql
          coverage: none

      - name: Tool versions
        run: |
          php --version
          composer --version

      - uses: ./.github/actions/cache-deps
        with:
          workflow_name: pr-code-coverage
          workflow_cache: ${{ secrets.WORKFLOW_CACHE }}

      - name: Install and Build
        uses: ./.github/actions/install-build
        
      - name: Build Admin feature config
        run: |
          pnpm nx build:feature-config woocommerce

      - name: Run Tests With Code Coverage
        run: |
          cd plugins/woocommerce
          composer require "wp-phpunit/wp-phpunit" "^5.9" --dev --no-scripts
          echo "{ \"phpVersion\": \"7.4\", \"core\": \"WordPress/WordPress#5.9\" }" > .wp-env.override.json
          npm -g install @wordpress/env
          wp-env start
          pnpm nx test-code-coverage woocommerce
          exit 0
      
      - name: Send code coverage to Codecov.
        run: |
          bash <(curl -s https://codecov.io/bash)
