name: Lint JS packages

on:
    pull_request:
        paths-ignore:
            - '**/changelog/**'
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions: {}

jobs:
    lint-test-js:
        name: Lint JS packages
        runs-on: ubuntu-20.04
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v3

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo

            - name: Lint
              run: pnpm run -r --filter='release-posts' --filter='woocommerce/client/admin...' --filter='@woocommerce/monorepo-utils' --filter='!@woocommerce/e2e*' --filter='!@woocommerce/api' --color lint

            - name: Collect and Combine Eslint Reports
              run: node ./github/workflows/scripts/collect-eslint-reports.js

            - name: Annotate Code Linting Results
              uses: ataylorme/eslint-annotate-action@v2
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  report-json: 'combined_eslint_report.json'
