name: MarkdownLint on PR
on:
    pull_request:
        paths-ignore:
            - '**/changelog/**'

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v37
              with:
                  files: |
                      **/*.md

            - name: Setup PNPM
              uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
              with:
                  version: '8.6.7'

            - name: Setup Node
              uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
              with:
                  node-version-file: .nvmrc
                  cache: pnpm
                  registry-url: 'https://registry.npmjs.org'

            - name: Install prerequisites
              run: |
                  pnpm i -g markdownlint-cli

            - name: Lint changed markdown files
              run: |
                  changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
                  lint_failed=false

                  if [ -n "$changed_files" ]; then
                    for file in $changed_files; do
                      lint_result=$(cat "$file" | markdownlint --stdin 2>&1)
                      if [ $? -ne 0 ]; then
                        echo "Lint failed for file: $file"
                        echo "$lint_result"
                        lint_failed=true
                      fi
                    done

                    if [ "$lint_failed" = true ]; then
                      echo "Linting failed for one or more files."
                      exit 1
                    else
                      echo "Linting successful for all files."
                    fi
                  else
                    echo "No markdown files changed."
                  fi
