name: Run unit tests on PR
on: 
  pull_request
defaults:
  run:
    shell: bash
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: PHP ${{ matrix.php }} WP ${{ matrix.wp }}
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.wp == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0' ]
        wp: [ "latest" ]
        include:
          - wp: nightly
            php: '7.4'
          - wp: '5.9'
            php: 7.2
          - wp: '5.8'
            php: 7.2
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/cache-deps
        with:
          workflow_name: pr-unit-tests
          workflow_cache: ${{ secrets.WORKFLOW_CACHE }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          extensions: mysql
          coverage: none

      - name: Tool versions
        run: |
          php --version
          composer --version

      - name: Install and Build
        uses: ./.github/actions/install-build

      - name: Build Admin feature config
        run: |
          pnpm nx build:feature-config woocommerce

      - name: Add PHP8 Compatibility.
        run: |
          if [ "$(php -r "echo version_compare(PHP_VERSION,'8.0','>=');")" ]; then
             cd plugins/woocommerce
             curl -L https://github.com/woocommerce/phpunit/archive/add-compatibility-with-php8-to-phpunit-7.zip -o /tmp/phpunit-7.5-fork.zip
             unzip -d /tmp/phpunit-7.5-fork /tmp/phpunit-7.5-fork.zip
             composer bin phpunit config --unset platform
             composer bin phpunit config repositories.0 '{"type": "path", "url": "/tmp/phpunit-7.5-fork/phpunit-add-compatibility-with-php8-to-phpunit-7", "options": {"symlink": false}}'
             composer bin phpunit require --dev -W phpunit/phpunit:@dev --ignore-platform-reqs
             rm -rf ./vendor/phpunit/
             pnpm nx composer-dump-autoload woocommerce
           fi

      - name: Run Tests
        run: |
          cd plugins/woocommerce
          WP_ENV_CORE="${{ matrix.wp }}"
          if [[ WP_ENV_CORE == 'latest' ]]; then
            WP_ENV_CORE="\"https://wordpress.org/latest.zip\""
          elif [[ WP_ENV_CORE == 'nightly' ]]; then
            WP_ENV_CORE="\"https://wordpress.org/nightly-builds/wordpress-latest.zip\""
          elif [[ WP_ENV_CORE == '5.8' ]]; then
            WP_ENV_CORE="\"https://wordpress.org/wordpress-5.8.4.zip\""
          elif [[ WP_ENV_CORE == '5.7' ]]; then
            WP_ENV_CORE="\"https://wordpress.org/wordpress-5.7.6.zip\""
          else
            WP_ENV_CORE="\"WordPress/WordPress#WP_ENV_CORE\""
          fi
          WP_ENV_PHP_VERSION="${{ matrix.php }}" pnpm wp-env start
          pnpm nx test-unit woocommerce
