name: "Enforce release code freeze"
on:
  schedule:
    - cron: '0 16 * * 4' # Run at 1600 UTC on Thursdays.
  workflow_dispatch:
    inputs:
      timeOverride:
        description: "Time Override: The time to use in checking whether the action should run (default: 'now')."
        default: 'now'
      skipSlackPing:
        description: "Skip Slack Ping: If true, the Slack ping will be skipped (useful for testing)"
        type: boolean
      slackChannelOverride:
        description: "Slack Channel Override: The channel ID to send the Slack ping about the freeze"

env:
    TIME_OVERRIDE: ${{ inputs.timeOverride }}
    GIT_COMMITTER_NAME: 'WooCommerce Bot'
    GIT_COMMITTER_EMAIL: 'no-reply@woocommerce.com'
    GIT_AUTHOR_NAME: 'WooCommerce Bot'
    GIT_AUTHOR_EMAIL: 'no-reply@woocommerce.com'

jobs:

  notify-slack:
    name: "Sends code freeze notification to Slack"
    if: ${{ inputs.skipSlackPing != true }}
    runs-on: ubuntu-20.04
    steps:
      - name: Slack
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
          slack-channel: ${{ inputs.slackChannelOverride || secrets.WOO_RELEASE_SLACK_CHANNEL }}
          slack-text: |
            :warning-8c: 6.8 Code Freeze :ice_cube:
            
            The automation to cut the release branch for 6.8 has run. Any PRs that were not already merged will be a part of 6.9 by default. If you have something that needs to make 6.8 that hasn't yet been merged, please see the <${{ secrets.FG_LINK }}/code-freeze-for-woocommerce-core-release/|fieldguide page for the code freeze>.
