name: "Enforce release code freeze"
on:
  workflow_dispatch:
    inputs:
      timeOverride:
        description: "Time Override: The time to use in checking whether the action should run (default: 'now')."
        default: 'now'
      skipSlackPing:
        description: "Skip Slack Ping: If true, the Slack ping will be skipped (useful for testing)"
        type: boolean
      slackChannelOverride:
        description: "Slack Channel Override: The channel ID to send the Slack ping about the freeze"

env:
    TIME_OVERRIDE: ${{ inputs.timeOverride }}
    GIT_COMMITTER_NAME: 'WooCommerce Bot'
    GIT_COMMITTER_EMAIL: 'no-reply@woocommerce.com'
    GIT_AUTHOR_NAME: 'WooCommerce Bot'
    GIT_AUTHOR_EMAIL: 'no-reply@woocommerce.com'

jobs:
  maybe-create-next-milestone-and-release-branch:
    name: "Maybe create next milestone and release branch"
    runs-on: ubuntu-20.04
    outputs:
      branch: ${{ steps.freeze.outputs.branch }}
      release_version: ${{ steps.freeze.outputs.release_version }}
      next_version: ${{ steps.freeze.outputs.next_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - uses: ./.github/actions/cache-deps
        with:
          workflow_name: release-code-freeze
          workflow_cache: ${{ secrets.WORKFLOW_CACHE }}

      - name: Install PNPM
        run: npm install -g pnpm@^6.24.2

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer

      - name: Install dependencies
        run: pnpm install

      - name: "Git fetch the newly created release branch"
        run: git fetch origin release/6.8
        
      - name: "Checkout the release branch"
        run: git checkout release/6.8
      
      - name: "Create a new branch for the changelog update PR"
        run: git checkout -b ${{ format( 'update/{0}-changelog', '6.8' ) }}

      - name: "Generate the changelog file"
        run: pnpm changelog --filter=woocommerce -- write --add-pr-num -n -vvv --use-version 6.8
        
      - name: "git rm deleted files"
        run: git ls-files --deleted -z | xargs -0 git rm
        
      - name: "Commit deletion"
        run: git commit -m "Delete changelog files from 6.8 release"
        
      - name: "Remember the deletion commit hash"
        id: rev-parse
        run: echo "::set-output name=hash::$(git rev-parse HEAD)"
        
      - name: "Insert NEXT_CHANGELOG contents into changelog and readme"
        run: php .github/workflows/scripts/release-changelog.php
      
      - name: "git add changelog and readme files"
        run: git add changelog.txt plugins/woocommerce/readme.txt
      
      - name: "Commit changelog and readme files"
        run: git commit -m "Update the changelog and readme files for the 6.8 release"
        
      - name: "Push update branch to origin"
        run: git push origin ${{ format( 'update/{0}-changelog', '6.8' ) }}
        
      - name: "Stash any other undesired changes"
        run: git stash
        
      - run: git fetch trunk
        
      - name: "Checkout trunk"
        run: git checkout trunk
      
      - name: "Create a branch for the changelog files deletion"
        run: git checkout -b ${{ format( 'delete/{0}-changelog', '6.8' ) }}
        
      - name: "Cherry-pick the deletion commit"
        run: git cherry-pick ${{ steps.rev-parse.outputs.hash }}
        
      - name: "Push deletion branch to origin"
        run: git push origin ${{ format( 'delete/{0}-changelog', '6.8' ) }}
        
      - name: "Create release branch PR"
        id: release-pr
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.pulls.create( {
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.event.repository.name }}",
              head: "${{ format( 'update/{0}-changelog', '6.8' ) }}",
              base: "release/6.8",
              title: "${{ format( 'Release: Prepare the changelog for {0}', '6.8' ) }}",
              body: "${{ format( 'This pull request was automatically generated during the code freeze to prepare the changelog for {0}', '6.8' ) }}"
            } );
            
            return result.data.number;

      - run: echo '${{ steps.release-pr.outputs.result }}'
            
      - name: "Create trunk PR"
        id: trunk-pr
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.pulls.create( {
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.event.repository.name }}",
              head: "${{ format( 'delete/{0}-changelog', '6.8' ) }}",
              base: "trunk",
              title: "${{ format( 'Release: Remove {0} change files', '6.8' ) }}",
              body: "${{ format( 'This pull request was automatically generated during the code freeze to remove the changefiles from {0} that are compiled into the `{1}` branch via #{2}', '6.8', 'release/6.8', steps.release-pr.outputs.result ) }}"
            } );
            
            return result.data.number;
