name: Install Dependencies (Reusable)
on:
  workflow_call:

jobs:
  install-deps:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
            access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: List checkout code
        run: ls ./plugins/woocommerce

      - name: Copy deps configuration to root.
        run: mkdir ./woo-cache && cp ./plugins/woocommerce/package-lock.json ./woo-cache && cp ./plugins/woocommerce/composer.lock ./woo-cache

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./woo-cache/node_modules
            ./woo-cache/vendor
          key: ${{ runner.os }}-install-deps-${{ hashFiles('./woo-cache/package-lock.json', './woo-cache/composer.lock') }}

      - name: Install PNPM
        run: npm install pnpm -g

      - name: Install node dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Install Composer
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: pnpm nx composer-install woocommerce

      - name: Check cache after install
        run: ls ./woo-cache
