name: Run tests on PR merge to trunk
on:
    push:
        branch:
            - 'e2e/on-trunk-merge-0'

concurrency:
    group: trunk-merge-${{ github.sha }}
    cancel-in-progress: true

permissions: {}

jobs:
    e2e:
        name: Run E2E tests.
        runs-on: ubuntu-20.04
        permissions:
            contents: read
        env:
            ALLURE_RESULTS_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/e2e-pw/test-results/allure-results
            ALLURE_REPORT_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/e2e-pw/test-results/allure-report
            ARTIFACT_NAME: e2e-trunk-commit-${{ github.sha }}-run-${{ github.run_number }}
        steps:
            - uses: actions/checkout@v3

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                  build-filters: woocommerce

            - name: Setup E2E local environment
              uses: ./.github/actions/tests/setup-e2e-local-environment

            - name: Run E2E tests
              id: e2e-action
              timeout-minutes: 60
              uses: ./.github/actions/tests/run-e2e
              with:
                  report-name: ${{ env.ARTIFACT_NAME }}

            - name: Upload Allure files to bucket
              if: success() || ( failure() && steps.e2e-action.conclusion == 'failure' )
              uses: ./.github/actions/tests/upload-allure-files-to-bucket
              with:
                  aws-access-key-id: ${{ secrets.REPORTS_AWS_ACCESS_KEY_ID }}
                  aws-region: ${{ secrets.REPORTS_AWS_REGION }}
                  aws-secret-access-key: ${{ secrets.REPORTS_AWS_SECRET_ACCESS_KEY }}
                  destination-dir: ${{ env.ARTIFACT_NAME }}
                  s3-bucket: ${{ secrets.REPORTS_BUCKET }}

            - name: Publish Allure report
              if: success() || ( failure() && steps.e2e-action.conclusion == 'failure' )
              env:
                  GITHUB_TOKEN: ${{ secrets.REPORTS_TOKEN }}
              run: |
                  gh workflow run publish-test-reports-trunk-merge.yml \
                  -f run_id=${{ github.run_id }} \
                  -f artifact=${{ env.ARTIFACT_NAME }} \
                  -f sha=${{ github.sha }} \
                  -f test_type="e2e" \
                  --repo woocommerce/woocommerce-test-reports
