name: 'Process stale issues and PRs'
on:
    schedule:
        - cron: '21 0 * * *'
    workflow_dispatch:
    pull_request:
        types: [converted_to_draft]

permissions: {}

jobs:
    stale:
        runs-on: ubuntu-20.04
        permissions:
            contents: read
            issues: write
            pull-requests: write
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        steps:
            - name: Process stale issues
              uses: actions/stale@v9.0.0
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  stale-issue-message: "As a part of this repository's maintenance, this issue is being marked as stale due to inactivity. Please feel free to comment on it in case we missed something.\n\n###### After 7 days with no activity this issue will be automatically be closed."
                  close-issue-message: 'This issue was closed because it has been 14 days with no activity.'
                  operations-per-run: 140
                  days-before-stale: -1
                  days-before-close: -1
                  days-before-issue-stale: 7
                  days-before-issue-close: 7
                  stale-issue-label: 'status: stale'
                  stale-pr-label: 'status: stale'
                  exempt-issue-labels: 'type: enhancement'
                  only-issue-labels: 'needs: author feedback'
                  close-issue-label: "status: can't reproduce"
                  ascending: true
            - name: Process stale flaky tests issues
              uses: actions/stale@v9.0.0
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  only-issue-labels: 'metric: flaky e2e test'
                  exempt-issue-labels: 'type: skipped test'
                  days-before-stale: -1
                  days-before-close: -1
                  days-before-issue-stale: 5
                  days-before-issue-close: 2
                  stale-issue-label: 'status: stale'
                  stale-issue-message: 'This issue is being marked as stale due to inactivity. It will be auto-closed if no further activity occurs within the next 2 days.'
                  close-issue-message: 'Auto-closed due to inactivity. Please re-open if you believe this issue is still valid.'
                  close-issue-reason: 'not_planned'
                  remove-stale-when-updated: true
                  exempt-all-assignees: false
                  enable-statistics: true
                  ascending: true
                  operations-per-run: 120
            - name: Remove stale PR approvals (over 30 days old)
              uses: actions/stale@v9.0.0
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  only-pr-labels: '*'
                  days-before-stale: -1
                  days-before-close: -1
                  days-before-pr-stale: 30
                  days-before-pr-close: -1
                  stale-pr-message: 'This PR approval has been removed due to being stale (30+ days old). Please request a new review.'
                  operations-per-run: 120
                  ascending: true

    remove-draft-approvals:
        runs-on: ubuntu-20.04
        permissions:
            pull-requests: write
        if: github.event_name == 'pull_request' && github.event.action == 'converted_to_draft'
        steps:
            - name: Remove approvals from draft PR
              uses: actions/stale@v9.0.0
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  only-pr-labels: '*'
                  days-before-stale: -1
                  days-before-close: -1
                  days-before-pr-stale: 0
                  days-before-pr-close: -1
                  operations-per-run: 120
                  stale-pr-message: 'This PR approval has been removed due to it being moved back to draft status after being approved. Please request a new review.'
                  ascending: true
