name: Storybook GitHub Pages

on:
    push:
        branches:
            - trunk
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'woocommerce/woocommerce' }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: trunk
                  fetch-depth: 0

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo

            - name: Build Storybook
              run: pnpm --filter='@woocommerce/storybook' build-storybook

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./tools/storybook/storybook-static
                  force_orphan: true
