name: Send PRs that require further testing to Slack
on:
  pull_request_target:
    types: [labeled]

permissions: {}

jobs:
  send-pr-to-slack-for-further-testing:
    if: "${{ github.event.label.name == 'needs: analysis' }}"
    runs-on: ubuntu-20.04
    steps:
      - name: Get the PR status
        id: get_pr_status
        run: |
          pr_status=${{ github.event.pull_request.merged == true && 'merged' || 'open' }}
          echo "pr_status=$pr_status" >> $GITHUB_OUTPUT
      - name: Calculate SLA timestamp
        id: calculate_sla
        run: |
          sla_timestamp=$(date -d "${{ github.event.label.created_at }} + 5 hours" -u +%s)
          echo "sla_timestamp=$sla_timestamp" >> $GITHUB_OUTPUT
      - name: Inspect
        env:
            JSON: ${{ toJson(github.event.label) }}
        run: echo "${{ env.JSON }}"
