name: Test workflow
on: pull_request
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    test:
        name: Test workflow.
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code.
              uses: actions/checkout@v3

            - name: Install PNPM
              run: npm install -g pnpm@^6.24.2

            - name: Install dependencies
              run: pnpm install

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '7.4'

            - name: Install composer
              run: pnpm nx composer-install woocommerce

            - name: Run build
              run: pnpm nx build woocommerce

            - name: Cache modules
              uses: actions/cache@v3
              id: cache-deps
              with:
                path: |
                  ~/.pnpm-store
                  plugins/woocommerce/packages
                  plugins/woocommerce/**/vendor
                key: ${{ runner.os }}-testtesttest3-version-${{ secrets.WORKFLOW_CACHE }}-${{ hashFiles('**/composer.lock', '**/pnpm-lock.yaml') }}

            - name: List dirs
              run: ls -R ~/
