name: 'Release checks'
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  pull_request:

jobs:
  run-tests:
    name: 'Run tests'
    uses: ./.github/workflows/ci.yml
    with:
      trigger: 'release-checks'
      tag: 'nightly'
    secrets: inherit
