name: 'Release checks'
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  pull_request:

jobs:
  run-tests:
    name: 'Run tests'
    if: ${{ GITHUB_REF_TYPE == 'tag' && GITHUB_REF_NAME != 'nightly' }}
    uses: ./.github/workflows/ci.yml
    with:
      trigger: 'release-checks'
      tag: ${{ GITHUB_REF_NAME }}
      artifact-name: 'woocommerce.zip'
    secrets: inherit
