name: 'Release checks'
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    
jobs:
  run-tests:
    name: 'Run tests'
    uses: ./.github/workflows/ci.yml
    with:
      trigger: 'release-checks'
      tag: ${{ github.ref }}
    secrets: inherit
