name: 'On demand tests run'

on:
  workflow_dispatch:
    inputs:
      trigger:
        type: choice
        description: 'Event name. It will be used to filter the jobs to run in ci.yml.'
        required: true
        options:
          - pull_request
          - push
          - daily-checks
          - pre-release
          - on-demand
          - custom
        default: on-demand
      custom-trigger:
        type: string
        description: 'Custom event name. In case the `Event name` choice is `custom`, this field is required.'
        required: false
        
concurrency:
  group: ${{ inputs.trigger }}-${{ inputs.custom-trigger }}
  cancel-in-progress: true

jobs:
  validate-input:
    runs-on: ubuntu-latest
    steps:
      - name: 'Validate input'
        run: |
          if [ "${{ inputs.trigger }}" == "custom" ] && [ -z "${{ inputs.custom-trigger }}" ]; then
            echo "Custom trigger is required when trigger is set to custom."
            exit 1
          fi

  run-tests:
    name: 'Run tests'
    uses: ./.github/workflows/ci.yml
    with:
      trigger: ${{ inputs.trigger == 'custom' && inputs.custom-trigger || inputs.trigger }}
    secrets: inherit
