name: 'Daily tests run'
on:
  schedule:
    - cron: '25 3 * * *'
  workflow_dispatch:
  pull_request:
    branches:
      - 'ci/fix-reporting-step-for-daily-e2e-runs'

jobs:
  run-tests:
    name: 'Run tests'
    uses: ./.github/workflows/ci.yml
    with:
      trigger: 'daily-e2e'
