name: Add Triage Label

on:
    issues:
        types: opened

jobs:
    add_label:
        runs-on: 20.04.4
        steps:
            - uses: actions/checkout@v3
            - uses: actions-ecosystem/action-add-labels@v1
              if: github.event.issue.labels[0] == null
              with:
                  labels: 'status: awaiting triage'
