on:
  pull_request:
    types: [opened, edited, synchronize]
  
jobs:
  try:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: 35084,
              team_reviewers: ['atlas'],
            });
